import { League_Spartan } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
// import useScrollRestoration from "./components/useScrollRestoration";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // useScrollRestoration();

  return (
    <html lang="en">
      {/* <useScrollRestoration/> */}
      <body className={leagueSpartan.className}>{children}</body>
    </html>
  );
}
